name: CI

on:
  pull_request:
    branches: ["dev"]

jobs:
  check_is_valid_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name is valid
        if: "!contains(github.ref, 'merge-dev')"
        run: |
          echo "This branch is not valid to merge develeop"
          exit 1
