# name: CI

# on:
#   pull_request:
#     branches: ["develop"]

# jobs:
#   check_is_valid_branch:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check if branch name is valid
#         if: "!contains(github.ref, 'merge-dev')"
#         run: |
#           echo ${{ github.ref }}
#           echo ${{ contains(github.ref,'merge-dev') }}
#           echo ${{ !contains(github.ref,'merge-dev') }}
#           echo "This branch is not valid to merge develeop"
#           exit 1

name: test

on: push

jobs:
  check_is_valid_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name is valid
        run: |
          echo ${{ github.ref }}
          echo ${{ contains(github.ref,'merge-dev') }}
          echo ${{ !contains(github.ref,'merge-dev') }}
          echo "This branch is not valid to merge develeop"
          exit 1
