name: release_merge_test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    branches: ["release"]

jobs:
  check_is_valid_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name is valid
        if: ${{ !contains(github.head_ref,'/main') && !contains(github.head_ref,'hotfix') }}
        run: |
          echo "This branch is not valid to merge develeop. Only branches with '/main' or 'hotfix' are allowed to merge to 'release'."
          exit 1

  check_is_valid_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is valid
        if: ${{ !contains(github.event.pull_request.labels.*.name,'release') }}
        run: |
          echo "This PR is not valid to merge develeop. Only PR with 'release' label is allowed to merge to 'release'."
          exit 1
