name: release_merge_test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    branches: ["release"]

jobs:
  check_is_valid_release_merge_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the branch name is valid for release merge
        if: ${{ contains(github.head_ref,'merge-dev') || (!contains(github.head_ref,'/main') && !contains(github.head_ref,'hotfix')) }}
        run: |
          echo "Branch ${{ github.head_ref }} is not valid to merge develeop. Only branches with '/main' or 'hotfix' are allowed to merge to 'release'."
          exit 1

  check_is_label_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label name is release
        if: ${{ !contains(github.event.pull_request.labels.*.name,'release') }}
        run: |
          echo "This PR is not valid to merge develeop. Only PR with 'release' label is allowed to merge to 'release'."
          exit 1
